// This file contains all of the data for each joker.
// The data is stored in a dictionary, with the key being the joker's name.
// Each joker has a name, description, rarity, and a list of synergies.
// The synergies list contains the names of other jokers that the current joker has synergy with.

// Rarity values: 0 = Common, 1 = Uncommon, 2 = Rare, 3 = Legendary

export const jokerdata = {
  "Lucky Cat": {
    name: "Lucky Cat",
    description:
      "This Joker gains X0.25 Mult every time a Lucky card successfully triggers",
    rarity: 1,
    synergies: [
      "Baseball Card",
      "Bloodstone",
      "Cartomancer",
      "Certificate",
      "Dusk",
      "Glass Joker",
      "Golden Ticket",
      "Hack",
      "Hanging Chad",
      "Oops! All 6s",
      "Red Card",
      "Sock and Buskin",
      "Steel Joker",
      "Stone Joker",
    ],
  },
  Seance: {
    name: "Seance",
    description:
      "If poker hand is a Straight Flush, create a random Spectral card (Must have room)",
    rarity: 1,
    synergies: [
      "Arrowhead",
      "Bloodstone",
      "Blueprint",
      "Brainstorm",
      "Crazy Joker",
      "Credit Card",
      "DNA",
      "Driver's License",
      "Drunkard",
      "Erosion",
      "Fibonacci",
      "Four Fingers",
      "Hit the Road",
      "Hologram",
      "Joker Stencil",
      "Juggler",
      "Merry Andy",
      "Onyx Agate",
      "Perkeo",
      "Scholar",
      "Shortcut",
      "Smeared Joker",
      "The Family",
      "Troubadour",
      "Vampire",
      "Wee Joker",
    ],
  },
  "Oops! All 6s": {
    name: "Oops! All 6s",
    description: "Doubles all listed probabilities (ex: 1 in 3 -> 2 in 3)",
    rarity: 1,
    synergies: [
      "8 Ball",
      "Baseball Card",
      "Bloodstone",
      "Business Card",
      "Cavendish",
      "Glass Joker",
      "Gros Michel",
      "Hallucination",
      "Hanging Chad",
      "Lucky Cat",
      "Lusty Joker",
      "Reserved Parking",
      "Sock and Buskin",
      "Space Joker",
    ],
  },
  Canio: {
    name: "Canio",
    description: "This Joker gains X1 Mult when a face card is destroyed",
    rarity: 3,
    synergies: [
      "Business Card",
      "Cavendish",
      "Chicot",
      "Erosion",
      "Glass Joker",
      "Hologram",
      "Pareidolia",
      "Perkeo",
      "Trading Card",
      "Triboulet",
      "Yorick",
    ],
  },
  "To Do List": {
    name: "To Do List",
    description:
      "Earn $4 if poker hand is a [Poker Hand], poker hand changes at end of round",
    rarity: 0,
    synergies: ["Blueprint", "Brainstorm"],
  },
  "Riff-Raff": {
    name: "Riff-Raff",
    description:
      "When Blind is selected, create 2 Common Jokers (Must have room)",
    rarity: 0,
    synergies: ["Abstract Joker", "Cavendish", "Gros Michel"],
  },
  "Reserved Parking": {
    name: "Reserved Parking",
    description:
      "This Joker gains +1 Mult per consecutive hand played without a scoring face card",
    rarity: 0,
    synergies: [
      "Baron",
      "Business Card",
      "Half Joker",
      "Midas Mask",
      "Mime",
      "Oops! All 6s",
      "Pareidolia",
      "Ride the Bus",
      "Shoot the Moon",
      "Smiley Face",
    ],
  },
  "Red Card": {
    name: "Red Card",
    description: "This Joker gains +3 Mult when any Booster Pack is skipped",
    rarity: 0,
    synergies: [
      "Astronomer",
      "Bloodstone",
      "Business Card",
      "Campfire",
      "Constellation",
      "Driver's License",
      "Flash Card",
      "Fortune Teller",
      "Hallucination",
      "Hologram",
      "Lucky Cat",
      "Matador",
      "Rocket",
      "Satellite",
      "Steel Joker",
      "Throwback",
      "Vampire",
    ],
  },
  "Gros Michel": {
    name: "Gros Michel",
    description:
      "+15 Mult 1 in 6 chance this is destroyed at the end of round.",
    rarity: 0,
    synergies: ["Cavendish", "Oops! All 6s", "Riff-Raff"],
  },
  "Midas Mask": {
    name: "Midas Mask",
    description: "All played face cards become Gold cards when scored",
    rarity: 1,
    synergies: [
      "Baron",
      "Business Card",
      "Driver's License",
      "Golden Ticket",
      "Mime",
      "Pareidolia",
      "Reserved Parking",
      "Ride the Bus",
      "Scary Face",
      "Shoot the Moon",
      "Smiley Face",
      "Vampire",
    ],
  },
  Rocket: {
    name: "Rocket",
    description:
      "Earn $1 at end of round. Payout increases by $2 when Boss Blind is defeated",
    rarity: 1,
    synergies: [
      "Baseball Card",
      "Bootstraps",
      "Bull",
      "Flash Card",
      "Red Card",
    ],
  },
  Hack: {
    name: "Hack",
    description: "Retrigger each played 2, 3, 4, or 5",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Bloodstone",
      "Blueprint",
      "Brainstorm",
      "Cartomancer",
      "Certificate",
      "DNA",
      "Dusk",
      "Fibonacci",
      "Glass Joker",
      "Greedy Joker",
      "Hiker",
      "Lucky Cat",
      "Odd Todd",
      "Ride the Bus",
      "Seltzer",
      "Showman",
      "The Idol",
      "Trading Card",
      "Vagabond",
      "Walkie Talkie",
      "Wee Joker",
    ],
  },
  "Marble Joker": {
    name: "Marble Joker",
    description: "Adds one Stone card to the deck when Blind is selected",
    rarity: 1,
    synergies: [
      "Bootstraps",
      "Burglar",
      "Burnt Joker",
      "Driver's License",
      "Flash Card",
      "Four Fingers",
      "Half Joker",
      "Hologram",
      "Ride the Bus",
      "Space Joker",
      "Stone Joker",
      "Supernova",
      "Vampire",
    ],
  },
  "Devious Joker": {
    name: "Devious Joker",
    description: "+100 Chips if played hand contains a Straight",
    rarity: 0,
    synergies: [
      "Crazy Joker",
      "Four Fingers",
      "Runner",
      "Seance",
      "Shortcut",
      "The Order",
    ],
  },
  "The Family": {
    name: "The Family",
    description: "X4 Mult if played hand contains a Four of a Kind",
    rarity: 2,
    synergies: [
      "Cloud 9",
      "Flower Pot",
      "Greedy Joker",
      "Seance",
      "The Duo",
      "The Order",
      "The Tribe",
      "The Trio",
      "Walkie Talkie",
    ],
  },
  "Odd Todd": {
    name: "Odd Todd",
    description:
      "Played cards with odd rank give +31 Chips when scored (A, 9, 7, 5, 3)",
    rarity: 0,
    synergies: [
      "Cloud 9",
      "DNA",
      "Even Steven",
      "Fibonacci",
      "Hack",
      "Ride the Bus",
      "Runner",
      "Scholar",
      "Shortcut",
      "Trading Card",
    ],
  },
  "Space Joker": {
    name: "Space Joker",
    description: "1 in 4 chance to upgrade level of played poker hand",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Blueprint",
      "Brainstorm",
      "Burglar",
      "Burnt Joker",
      "Certificate",
      "Crazy Joker",
      "Green Joker",
      "Half Joker",
      "Marble Joker",
      "Oops! All 6s",
      "Ramen",
      "Spare Trousers",
      "Supernova",
    ],
  },
  Satellite: {
    name: "Satellite",
    description: "Earn $1 at end of round per unique Planet card used this run",
    rarity: 1,
    synergies: ["Astronomer", "Constellation", "Red Card"],
  },
  "Smiley Face": {
    name: "Smiley Face",
    description: "Played face cards give +5 Mult when scored",
    rarity: 0,
    synergies: [
      "Baron",
      "Business Card",
      "Midas Mask",
      "Pareidolia",
      "Reserved Parking",
      "Ride the Bus",
      "Scary Face",
      "Shoot the Moon",
      "Sock and Buskin",
      "Splash",
      "Steel Joker",
      "Triboulet",
    ],
  },
  "Delayed Gratification": {
    name: "Delayed Gratification",
    description:
      "Earn $2 per discard if no discards are used by end of the round",
    rarity: 0,
    synergies: [
      "Banner",
      "Castle",
      "Drunkard",
      "Four Fingers",
      "Green Joker",
      "Jolly Joker",
      "Merry Andy",
      "Ramen",
      "Shortcut",
      "Smeared Joker",
    ],
  },
  "Hit the Road": {
    name: "Hit the Road",
    description:
      "This Joker gains X0.5 Mult for every Jack discarded this round",
    rarity: 2,
    synergies: [
      "Blueprint",
      "Brainstorm",
      "Certificate",
      "DNA",
      "Drunkard",
      "Merry Andy",
      "Seance",
      "Yorick",
    ],
  },
  Madness: {
    name: "Madness",
    description:
      "When Small Blind or Big Blind is selected, gain X0.5 Mult and destroy a random Joker",
    rarity: 1,
    synergies: ["Abstract Joker", "Obelisk", "Pareidolia"],
  },
  "Crazy Joker": {
    name: "Crazy Joker",
    description: "+12 Mult if played hand contains a Straight",
    rarity: 0,
    synergies: [
      "Card Sharp",
      "Droll Joker",
      "Four Fingers",
      "Jolly Joker",
      "Mad Joker",
      "Runner",
      "Seance",
      "Shortcut",
      "Space Joker",
      "Supernova",
      "Superposition",
      "Seance",
      "The Order",
      "Zany Joker",
    ],
  },
  "Chaos the Clown": {
    name: "Chaos the Clown",
    description: "1 free Reroll per shop",
    rarity: 0,
    synergies: ["Astronomer", "Campfire", "Constellation", "Flash Card"],
  },
  "Stone Joker": {
    name: "Stone Joker",
    description: "Gives +25 Chips for each Stone Card in your full deck",
    rarity: 1,
    synergies: [
      "Blueprint",
      "Cartomancer",
      "DNA",
      "Glass Joker",
      "Golden Ticket",
      "Half Joker",
      "Lucky Cat",
      "Marble Joker",
      "Steel Joker",
    ],
  },
  Cavendish: {
    name: "Cavendish",
    description:
      "X3 Mult 1 in 1000 chance this card is destroyed at the end of round",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Blueprint",
      "Brainstorm",
      "Canio",
      "Flash Card",
      "Fortune Teller",
      "Gros Michel",
      "Oops! All 6s",
      "Riff-Raff",
    ],
  },
  Cartomancer: {
    name: "Cartomancer",
    description: "Create a Tarot card when Blind is selected",
    rarity: 1,
    synergies: [
      "Astronomer",
      "Blueprint",
      "Brainstorm",
      "Burglar",
      "Campfire",
      "Cloud 9",
      "Fortune Teller",
      "Gift Card",
      "Glass Joker",
      "Golden Ticket",
      "Greedy Joker",
      "Green Joker",
      "Hack",
      "Luchador",
      "Lucky Cat",
      "Obelisk",
      "Perkeo",
      "Ride the Bus",
      "Runner",
      "Spare Trousers",
      "Square Joker",
      "Steel Joker",
      "Stone Joker",
      "Supernova",
      "Wee Joker",
    ],
  },
  "Flower Pot": {
    name: "Flower Pot",
    description:
      "X3 Mult if poker hand contains a Diamond suit icon Diamond card, Club suit icon Club card, Heart suit icon Heart card, and Spade suit icon Spade card",
    rarity: 1,
    synergies: [
      "Seeing Double",
      "Smeared Joker",
      "Splash",
      "The Family",
      "The Order",
      "Walkie Talkie",
    ],
  },
  "Wee Joker": {
    name: "Wee Joker",
    description: "This Joker gains +8 Chips when each played 2 is scored",
    rarity: 2,
    synergies: [
      "Ancient Joker",
      "Bloodstone",
      "Burnt Joker",
      "Cartomancer",
      "Certificate",
      "DNA",
      "Drunkard",
      "Even Steven",
      "Fibonacci",
      "Glass Joker",
      "Hack",
      "Half Joker",
      "Hanging Chad",
      "Hologram",
      "Ice Cream",
      "Joker",
      "Merry Andy",
      "Photograph",
      "Seance",
      "Square Joker",
      "Trading Card",
    ],
  },
  "Flash Card": {
    name: "Flash Card",
    description: "This Joker gains +2 Mult per reroll in the shop",
    rarity: 1,
    synergies: [
      "Campfire",
      "Cavendish",
      "Certificate",
      "Chaos the Clown",
      "Cloud 9",
      "Constellation",
      "Golden Joker",
      "Marble Joker",
      "Matador",
      "Red Card",
      "Rocket",
    ],
  },
  "8 Ball": {
    name: "8 Ball",
    description:
      "1 in 4 chance for each played 8 to create a Tarot card when scored",
    rarity: 0,
    synergies: [
      "Blueprint",
      "Brainstorm",
      "DNA",
      "Fortune Teller",
      "Oops! All 6s",
      "Perkeo",
    ],
  },
  Showman: {
    name: "Showman",
    description:
      "Joker, Tarot, Planet, and Spectral cards may appear multiple times",
    rarity: 1,
    synergies: ["Gift Card", "Hack", "Invisible Joker", "Mr. Bones"],
  },
  Baron: {
    name: "Baron",
    description: "Each King held in hand gives X1.5 Mult",
    rarity: 2,
    synergies: [
      "Certificate",
      "DNA",
      "Half Joker",
      "Juggler",
      "Midas Mask",
      "Mime",
      "Raised Fist",
      "Reserved Parking",
      "Shoot the Moon",
      "Smiley Face",
      "Troubadour",
    ],
  },
  Throwback: {
    name: "Throwback",
    description: "X0.25 Mult for each Blind skipped this run",
    rarity: 1,
    synergies: ["Ice Cream", "Red Card", "Turtle Bean"],
  },
  "Golden Joker": {
    name: "Golden Joker",
    description: "Earn $4 at end of round",
    rarity: 0,
    synergies: [
      "Bull",
      "Credit Card",
      "Flash Card",
      "Joker",
      "Ramen",
      "To the Moon",
    ],
  },
  "Onyx Agate": {
    name: "Onyx Agate",
    description:
      "Played cards with Club suit icon Club suit give +7 Mult when scored",
    rarity: 1,
    synergies: [
      "Arrowhead",
      "Blackboard",
      "Bloodstone",
      "Certificate",
      "Droll Joker",
      "Glass Joker",
      "Gluttonous Joker",
      "Photograph",
      "Rough Gem",
      "Seance",
      "Smeared Joker",
      "Steel Joker",
      "The Idol",
      "Triboulet",
    ],
  },
  "Jolly Joker": {
    name: "Jolly Joker",
    description: "+8 Mult if played hand contains a Pair",
    rarity: 0,
    synergies: [
      "Banner",
      "Burglar",
      "Crazy Joker",
      "Delayed Gratification",
      "Droll Joker",
      "Green Joker",
      "Half Joker",
      "Mad Joker",
      "Mystic Summit",
      "Spare Trousers",
      "Splash",
      "Square Joker",
      "Stuntman",
      "The Duo",
      "Walkie Talkie",
      "Zany Joker",
    ],
  },
  Brainstorm: {
    name: "Brainstorm",
    description: "Copies the ability of leftmost Joker",
    rarity: 2,
    synergies: [
      "8 Ball",
      "Ancient Joker",
      "Baseball Card",
      "Blueprint",
      "Burglar",
      "Burnt Joker",
      "Cartomancer",
      "Cavendish",
      "Ceremonial Dagger",
      "Certificate",
      "DNA",
      "Egg",
      "Faceless Joker",
      "Hack",
      "Hit the Road",
      "Loyalty Card",
      "Luchador",
      "Mime",
      "Mr. Bones",
      "Perkeo",
      "Seance",
      "Space Joker",
      "Stuntman",
      "To Do List",
    ],
  },
  Astronomer: {
    name: "Astronomer",
    description: "All Planet cards and Celestial Packs in the shop are free",
    rarity: 1,
    synergies: [
      "Campfire",
      "Cartomancer",
      "Chaos the Clown",
      "Constellation",
      "Ramen",
      "Red Card",
      "Satellite",
    ],
  },
  Mime: {
    name: "Mime",
    description: "Retrigger all card held in hand abilities",
    rarity: 1,
    synergies: [
      "Baron",
      "Blueprint",
      "Brainstorm",
      "Certificate",
      "Half Joker",
      "Juggler",
      "Merry Andy",
      "Midas Mask",
      "Raised Fist",
      "Reserved Parking",
      "Shoot the Moon",
      "Steel Joker",
      "Stuntman",
      "Troubadour",
    ],
  },
  "Card Sharp": {
    name: "Card Sharp",
    description:
      "X3 Mult if played poker hand has already been played this round",
    rarity: 1,
    synergies: [
      "Burglar",
      "Crazy Joker",
      "Drunkard",
      "Green Joker",
      "Half Joker",
      "Juggler",
      "Spare Trousers",
      "Supernova",
    ],
  },
  "Fortune Teller": {
    name: "Fortune Teller",
    description: "+1 Mult per Tarot card used this run",
    rarity: 0,
    synergies: [
      "8 Ball",
      "Cartomancer",
      "Cavendish",
      "Certificate",
      "Cloud 9",
      "Hallucination",
      "Perkeo",
      "Red Card",
      "Superposition",
      "Vagabond",
      "Vampire",
    ],
  },
  Bull: {
    name: "Bull",
    description: "+2 Chips for each $1 you have",
    rarity: 1,
    synergies: [
      "Bootstraps",
      "Certificate",
      "Cloud 9",
      "Golden Joker",
      "Matador",
      "Rocket",
    ],
  },
  Stuntman: {
    name: "Stuntman",
    description: "+250 Chips, -2 hand size",
    rarity: 2,
    synergies: [
      "Blackboard",
      "Blueprint",
      "Brainstorm",
      "Green Joker",
      "Half Joker",
      "Jolly Joker",
      "Juggler",
      "Mime",
      "Raised Fist",
      "Troubadour",
      "Turtle Bean",
    ],
  },
  Runner: {
    name: "Runner",
    description: "Gains +15 Chips if played hand contains a Straight",
    rarity: 0,
    synergies: [
      "Cartomancer",
      "Crazy Joker",
      "Four Fingers",
      "Odd Todd",
      "Shortcut",
      "Spare Trousers",
    ],
  },
  "Spare Trousers": {
    name: "Spare Trousers",
    description: "This Joker gains +2 Mult if played hand contains a Two Pair",
    rarity: 1,
    synergies: [
      "Burglar",
      "Card Sharp",
      "Cartomancer",
      "Jolly Joker",
      "Mad Joker",
      "Obelisk",
      "Runner",
      "Space Joker",
      "Square Joker",
      "Supernova",
      "Walkie Talkie",
    ],
  },
  "Loyalty Card": {
    name: "Loyalty Card",
    description: "X4 Mult every 6 hands played",
    rarity: 1,
    synergies: ["Acrobat", "Blueprint", "Brainstorm", "Burglar"],
  },
  "Hanging Chad": {
    name: "Hanging Chad",
    description:
      "Retrigger first played card used in scoring 2 additional times",
    rarity: 0,
    synergies: [
      "Bloodstone",
      "Lucky Cat",
      "Oops! All 6s",
      "Photograph",
      "Scary Face",
      "Scholar",
      "Walkie Talkie",
      "Wee Joker",
    ],
  },
  "Smeared Joker": {
    name: "Smeared Joker",
    description:
      "Heart suit icon Hearts and Diamond suit icon Diamonds count as the same suit, Spade suit icon Spades and Club suit icon Clubs count as the same suit",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Arrowhead",
      "Bloodstone",
      "Burnt Joker",
      "Castle",
      "Delayed Gratification",
      "Droll Joker",
      "Flower Pot",
      "Gluttonous Joker",
      "Greedy Joker",
      "Lusty Joker",
      "Onyx Agate",
      "Rough Gem",
      "Seance",
      "Seeing Double",
      "The Tribe",
      "Troubadour",
      "Walkie Talkie",
      "Wrathful Joker",
    ],
  },
  "Sixth Sense": {
    name: "Sixth Sense",
    description:
      "If first hand of round is a single 6, destroy it and create a Spectral card",
    rarity: 1,
    synergies: ["Baseball Card", "Credit Card", "DNA", "Perkeo"],
  },
  "Mad Joker": {
    name: "Mad Joker",
    description: "+10 Mult if played hand contains a Two Pair",
    rarity: 0,
    synergies: [
      "Crazy Joker",
      "Droll Joker",
      "Jolly Joker",
      "Spare Trousers",
      "Square Joker",
      "Walkie Talkie",
      "Zany Joker",
    ],
  },
  Bloodstone: {
    name: "Bloodstone",
    description:
      "1 in 2 chance for played cards with Heart suit icon Heart suit to give X1.5 Mult when scored",
    rarity: 1,
    synergies: [
      "Arrowhead",
      "Baseball Card",
      "Business Card",
      "Droll Joker",
      "Greedy Joker",
      "Hack",
      "Hallucination",
      "Hanging Chad",
      "Lucky Cat",
      "Lusty Joker",
      "Onyx Agate",
      "Oops! All 6s",
      "Red Card",
      "Rough Gem",
      "Seance",
      "Smeared Joker",
      "Sock and Buskin",
      "The Idol",
      "Triboulet",
      "Wee Joker",
    ],
  },
  "Trading Card": {
    name: "Trading Card",
    description:
      "If first discard of round has only 1 card, destroy it and earn $3",
    rarity: 1,
    synergies: [
      "Canio",
      "Castle",
      "Drunkard",
      "Erosion",
      "Glass Joker",
      "Hack",
      "Merry Andy",
      "Odd Todd",
      "Ride the Bus",
      "The Idol",
      "Wee Joker",
    ],
  },
  Pareidolia: {
    name: "Pareidolia",
    description: "All cards are considered face cards	",
    rarity: 1,
    synergies: [
      "Business Card",
      "Canio",
      "Ceremonial Dagger",
      "Chicot",
      "Faceless Joker",
      "Glass Joker",
      "Golden Ticket",
      "Luchador",
      "Madness",
      "Midas Mask",
      "Mr. Bones",
      "Photograph",
      "Popcorn",
      "Reserved Parking",
      "Ride the Bus",
      "Rough Gem",
      "Scary Face",
      "Smiley Face",
      "Sock and Buskin",
      "Splash",
      "Vampire",
    ],
  },
  "The Tribe": {
    name: "The Tribe",
    description: "X2 Mult if played hand contains a Flush",
    rarity: 2,
    synergies: [
      "Ancient Joker",
      "Droll Joker",
      "Four Fingers",
      "Gluttonous Joker",
      "Greedy Joker",
      "Smeared Joker",
      "The Duo",
      "The Family",
      "The Order",
      "The Trio",
      "Troubadour",
    ],
  },
  "Blue Joker": {
    name: "Blue Joker",
    description: "+2 Chips for each remaining card in deck",
    rarity: 0,
    synergies: ["DNA", "Green Joker", "Half Joker", "Ramen"],
  },
  Chicot: {
    name: "Chicot",
    description: "Disables effect of every Boss Blind",
    rarity: 3,
    synergies: ["Canio", "Luchador", "Pareidolia", "Perkeo", "Triboulet"],
  },
  "Burnt Joker": {
    name: "Burnt Joker",
    description:
      "Upgrade the level of the first discarded poker hand each round",
    rarity: 2,
    synergies: [
      "Ancient Joker",
      "Blueprint",
      "Brainstorm",
      "Castle",
      "Certificate",
      "Drunkard",
      "Four Fingers",
      "Half Joker",
      "Marble Joker",
      "Shortcut",
      "Smeared Joker",
      "Space Joker",
      "Steel Joker",
      "Supernova",
      "Wee Joker",
      "Yorick",
    ],
  },
  Blueprint: {
    name: "Blueprint",
    description: "Copies ability of Joker to the right",
    rarity: 2,
    synergies: [
      "8 Ball",
      "Acrobat",
      "Ancient Joker",
      "Baseball Card",
      "Blueprint",
      "Brainstorm",
      "Burglar",
      "Burnt Joker",
      "Business Card",
      "Cartomancer",
      "Cavendish",
      "Ceremonial Dagger",
      "Certificate",
      "DNA",
      "Egg",
      "Faceless Joker",
      "Hack",
      "Hit the Road",
      "Loyalty Card",
      "Luchador",
      "Mime",
      "Mr. Bones",
      "Perkeo",
      "Seance",
      "Space Joker",
      "Stone Joker",
      "Stuntman",
      "To Do List",
    ],
  },
  Dusk: {
    name: "Dusk",
    description: "Retrigger all played cards in final hand of the round",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Hack",
      "Lucky Cat",
      "Photograph",
      "The Idol",
      "Walkie Talkie",
    ],
  },
  "The Idol": {
    name: "The Idol",
    description:
      "Each played [rank] of [suit] gives X2 Mult when scored Card changes every round",
    rarity: 1,
    synergies: [
      "Bloodstone",
      "DNA",
      "Dusk",
      "Gluttonous Joker",
      "Greedy Joker",
      "Hack",
      "Lusty Joker",
      "Onyx Agate",
      "Photograph",
      "Sock and Buskin",
      "Splash",
      "Trading Card",
      "Vagabond",
    ],
  },
  Joker: {
    name: "Joker",
    description: "+4 Mult",
    rarity: 0,
    synergies: [
      "Credit Card",
      "Faceless Joker",
      "Golden Joker",
      "Steel Joker",
      "Wee Joker",
    ],
  },
  "Greedy Joker": {
    name: "Greedy Joker",
    description:
      "Played cards with Diamond suit icon Diamond suit give +3 Mult when scored",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Bloodstone",
      "Cartomancer",
      "Castle",
      "Droll Joker",
      "Gluttonous Joker",
      "Hack",
      "Lusty Joker",
      "Rough Gem",
      "Smeared Joker",
      "Sock and Buskin",
      "Splash",
      "Steel Joker",
      "Superposition",
      "The Family",
      "The Idol",
      "The Tribe",
      "Wrathful Joker",
    ],
  },
  "Steel Joker": {
    name: "Steel Joker",
    description: "Gives X0.2 Mult for each Steel Card in your full deck",
    rarity: 1,
    synergies: [
      "Burnt Joker",
      "Cartomancer",
      "DNA",
      "Even Steven",
      "Fibonacci",
      "Glass Joker",
      "Gluttonous Joker",
      "Golden Ticket",
      "Greedy Joker",
      "Half Joker",
      "Joker",
      "Lucky Cat",
      "Lusty Joker",
      "Mime",
      "Onyx Agate",
      "Red Card",
      "Scholar",
      "Smiley Face",
      "Stone Joker",
      "Walkie Talkie",
      "Wrathful Joker",
    ],
  },
  Matador: {
    name: "Matador",
    description: "Earn $8 if played hand triggers the Boss Blind ability",
    rarity: 0,
    synergies: [
      "Bootstraps",
      "Bull",
      "Burglar",
      "Flash Card",
      "Green Joker",
      "Red Card",
      "To the Moon",
    ],
  },
  "To the Moon": {
    name: "To the Moon",
    description:
      "Earn an extra $1 of interest for every $5 you have at end of round",
    rarity: 1,
    synergies: ["Baseball Card", "Bootstraps", "Golden Joker", "Matador"],
  },
  "Seeing Double": {
    name: "Seeing Double",
    description:
      "X2 Mult if played hand has a scoring Club suit icon Club card and a scoring card of any other suit",
    rarity: 1,
    synergies: ["Flower Pot", "Smeared Joker", "Splash", "Walkie Talkie"],
  },
  Shortcut: {
    name: "Shortcut",
    description:
      "Allows Straights to be made with gaps of 1 rank (ex: 10 8 6 5 3)",
    rarity: 1,
    synergies: [
      "Baseball Card",
      "Blackboard",
      "Burnt Joker",
      "Crazy Joker",
      "Delayed Gratification",
      "Four Fingers",
      "Odd Todd",
      "Runner",
      "Seance",
      "Superposition",
      "The Order",
      "Walkie Talkie",
    ],
  },
  Triboulet: {
    name: "Triboulet",
    description: "Played Kings and Queens each give X2 Mult when scored",
    rarity: 3,
    synergies: [
      "Bloodstone",
      "Business Card",
      "Canio",
      "Chicot",
      "Onyx Agate",
      "Perkeo",
      "Photograph",
      "Smiley Face",
      "Sock and Buskin",
      "Yorick",
    ],
  },
  "Clever Joker": {
    name: "Clever Joker",
    description: "+80 Chips if played hand contains a Two Pair",
    rarity: 0,
    synergies: [
      "Jolly Joker",
      "Mad Joker",
      "Spare Trousers",
      "Square Joker",
      "Walkie Talkie",
    ],
  },
  Fibonacci: {
    name: "Fibonacci",
    description: "Each played Ace, 2, 3, 5, or 8 gives +8 Mult when scored",
    rarity: 1,
    synergies: [
      "Certificate",
      "Hack",
      "Odd Todd",
      "Seance",
      "Scholar",
      "Steel Joker",
      "Wee Joker",
    ],
  },
  Troubadour: {
    name: "Troubadour",
    description: "+2 hand size, -1 hand per round",
    rarity: 1,
    synergies: [
      "Baron",
      "Half Joker",
      "Juggler",
      "Mime",
      "Seance",
      "Smeared Joker",
      "Stuntman",
      "The Tribe",
      "Turtle Bean",
    ],
  },
  "Sly Joker": {
    name: "Sly Joker",
    description: "+50 Chips if played hand contains a Pair",
    rarity: 0,
    synergies: [
      "Half Joker",
      "Jolly Joker",
      "Mad Joker",
      "The Duo",
      "Walkie Talkie",
    ],
  },
  Swashbuckler: {
    name: "Swashbuckler",
    description: "Adds the sell value of all other owned Jokers to Mult",
    rarity: 0,
    synergies: ["Egg", "Gift Card"],
  },
  Constellation: {
    name: "Constellation",
    description: "This Joker gains X0.1 Mult every time a Planet card is used",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Astronomer",
      "Certificate",
      "Chaos the Clown",
      "Flash Card",
      "Obelisk",
      "Perkeo",
      "Red Card",
      "Satellite",
    ],
  },
  Egg: {
    name: "Egg",
    description: "Gains $3 of sell value at end of round",
    rarity: 0,
    synergies: ["Blueprint", "Brainstorm", "Ceremonial Dagger", "Swashbuckler"],
  },
  Ramen: {
    name: "Ramen",
    description: "X2 Mult, loses X0.01 Mult per card discarded",
    rarity: 1,
    synergies: [
      "Abstract Joker",
      "Astronomer",
      "Banner",
      "Blue Joker",
      "Burglar",
      "Castle",
      "Delayed Gratification",
      "Golden Joker",
      "Green Joker",
      "Half Joker",
      "Popcorn",
      "Scholar",
      "Space Joker",
      "Turtle Bean",
      "Walkie Talkie",
    ],
  },
  Blackboard: {
    name: "Blackboard",
    description:
      "X3 Mult if all cards held in hand are Spade suit icon Spades or Club suit icon Clubs",
    rarity: 1,
    synergies: [
      "Baseball Card",
      "Four Fingers",
      "Onyx Agate",
      "Shortcut",
      "Stuntman",
    ],
  },
  "Gluttonous Joker": {
    name: "Gluttonous Joker",
    description:
      "Played cards with Club suit icon Club suit give +3 Mult when scored",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Castle",
      "Droll Joker",
      "Greedy Joker",
      "Lusty Joker",
      "Onyx Agate",
      "Smeared Joker",
      "Steel Joker",
      "The Idol",
      "The Tribe",
      "Wrathful Joker",
    ],
  },
  DNA: {
    name: "DNA",
    description:
      "If first hand of round has only 1 card, add a permanent copy to deck and draw it to hand",
    rarity: 2,
    synergies: [
      "8 Ball",
      "Ancient Joker",
      "Baron",
      "Blue Joker",
      "Blueprint",
      "Brainstorm",
      "Certificate",
      "Cloud 9",
      "Driver's License",
      "Glass Joker",
      "Hack",
      "Hit the Road",
      "Hologram",
      "Odd Todd",
      "Seance",
      "Scholar",
      "Shoot the Moon",
      "Sixth Sense",
      "Steel Joker",
      "Stone Joker",
      "The Idol",
      "Vampire",
      "Wee Joker",
    ],
  },
  "Golden Ticket": {
    name: "Golden Ticket",
    description: "Played Gold cards earn $4 when scored",
    rarity: 0,
    synergies: [
      "Cartomancer",
      "Lucky Cat",
      "Midas Mask",
      "Pareidolia",
      "Sock and Buskin",
      "Steel Joker",
      "Stone Joker",
    ],
  },
  "Diet Cola": {
    name: "Diet Cola",
    description: "Sell this card to create a free Double Tag",
    rarity: 1,
    synergies: ["Luchador"],
  },
  Vagabond: {
    name: "Vagabond",
    description: "Create a Tarot card if hand is played with $4 or less",
    rarity: 2,
    synergies: [
      "Burglar",
      "Credit Card",
      "Fortune Teller",
      "Green Joker",
      "Hack",
      "Perkeo",
      "The Idol",
    ],
  },
  Vampire: {
    name: "Vampire",
    description:
      "This Joker gains X0.1 Mult per scoring Enhanced card played, removes card Enhancement",
    rarity: 1,
    synergies: [
      "Certificate",
      "DNA",
      "Fortune Teller",
      "Green Joker",
      "Marble Joker",
      "Midas Mask",
      "Pareidolia",
      "Red Card",
      "Seance",
    ],
  },
  Acrobat: {
    name: "Acrobat",
    description: "X3 Mult on final hand of round",
    rarity: 1,
    synergies: ["Ancient Joker", "Blueprint", "Green Joker", "Loyalty Card"],
  },
  "Credit Card": {
    name: "Credit Card",
    description: "Go up to -$20 in debt",
    rarity: 0,
    synergies: [
      "Credit Card",
      "Golden Joker",
      "Joker",
      "Seance",
      "Sixth Sense",
      "Vagabond",
    ],
  },
  "Business Card": {
    name: "Business Card",
    description:
      "Played face cards have a 1 in 2 chance to give $2 when scored",
    rarity: 0,
    synergies: [
      "Bloodstone",
      "Blueprint",
      "Canio",
      "Midas Mask",
      "Oops! All 6s",
      "Pareidolia",
      "Red Card",
      "Reserved Parking",
      "Ride the Bus",
      "Scary Face",
      "Seltzer",
      "Smiley Face",
      "Sock and Buskin",
      "Splash",
      "Triboulet",
    ],
  },
  "The Order": {
    name: "The Order",
    description: "X3 Mult if played hand contains a Straight",
    rarity: 2,
    synergies: [
      "Crazy Joker",
      "Flower Pot",
      "Shortcut",
      "The Duo",
      "The Family",
      "The Tribe",
      "The Trio",
      "Walkie Talkie",
    ],
  },
  Popcorn: {
    name: "Popcorn",
    description: "+20 Mult -4 Mult per round played",
    rarity: 0,
    synergies: ["Ice Cream", "Pareidolia", "Ramen", "Turtle Bean"],
  },
  "Cloud 9": {
    name: "Cloud 9",
    description: "Earn $1 for each 9 in your full deck at end of round",
    rarity: 1,
    synergies: [
      "Baseball Card",
      "Bootstraps",
      "Bull",
      "Cartomancer",
      "DNA",
      "Flash Card",
      "Fortune Teller",
      "Hologram",
      "Odd Todd",
      "Perkeo",
      "The Family",
      "The Trio",
    ],
  },
  "Green Joker": {
    name: "Green Joker",
    description: "+1 Mult per hand played -1 Mult per discard",
    rarity: 0,
    synergies: [
      "Acrobat",
      "Banner",
      "Blue Joker",
      "Burglar",
      "Card Sharp",
      "Cartomancer",
      "Delayed Gratification",
      "Half Joker",
      "Hologram",
      "Jolly Joker",
      "Matador",
      "Ramen",
      "Space Joker",
      "Splash",
      "Square Joker",
      "Stuntman",
      "Supernova",
      "Vagabond",
      "Vampire",
    ],
  },
  "Crafty Joker": {
    name: "Crafty Joker",
    description: "+80 Chips if played hand contains a Flush",
    rarity: 0,
    synergies: [
      "Droll Joker",
      "Gluttonous Joker",
      "Greedy Joker",
      "Lusty Joker",
      "Smeared Joker",
      "The Tribe",
    ],
  },
  "Mr. Bones": {
    name: "Mr. Bones",
    description:
      "Prevents Death if chips scored are at least 25% of required chips self destructs",
    rarity: 1,
    synergies: ["Blueprint", "Brainstorm", "Pareidolia", "Showman"],
  },
  "Ceremonial Dagger": {
    name: "Ceremonial Dagger",
    description:
      "When Blind is selected, destroy Joker to the right and permanently add double its sell value to this Mult",
    rarity: 1,
    synergies: [
      "Abstract Joker",
      "Blueprint",
      "Brainstorm",
      "Egg",
      "Gift Card",
      "Pareidolia",
    ],
  },
  "Sock and Buskin": {
    name: "Sock and Buskin",
    description: "Retrigger all played face cards",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Bloodstone",
      "Business Card",
      "Golden Ticket",
      "Greedy Joker",
      "Lucky Cat",
      "Oops! All 6s",
      "Pareidolia",
      "Photograph",
      "Scary Face",
      "Smiley Face",
      "The Idol",
      "Triboulet",
      "Walkie Talkie",
    ],
  },
  "Four Fingers": {
    name: "Four Fingers",
    description: "All Flushes and Straights can be made with 4 cards",
    rarity: 1,
    synergies: [
      "Blackboard",
      "Burnt Joker",
      "Crazy Joker",
      "Delayed Gratification",
      "Droll Joker",
      "Four Fingers",
      "Marble Joker",
      "Runner",
      "Seance",
      "Shortcut",
      "Square Joker",
      "Superposition",
      "The Tribe",
    ],
  },
  "Merry Andy": {
    name: "Merry Andy",
    description: "+3 discards each round, -1 hand size	",
    rarity: 1,
    synergies: [
      "Banner",
      "Castle",
      "Delayed Gratification",
      "Faceless Joker",
      "Hit the Road",
      "Juggler",
      "Mime",
      "Seance",
      "Trading Card",
      "Wee Joker",
      "Yorick",
    ],
  },
  "Invisible Joker": {
    name: "Invisible Joker",
    description: "After 2 rounds, sell this card to Duplicate a random Joker",
    rarity: 2,
    synergies: ["Luchador", "Showman"],
  },
  "Mystic Summit": {
    name: "Mystic Summit",
    description: "+15 Mult when 0 discards remaining",
    rarity: 0,
    synergies: ["Burglar", "Jolly Joker", "Yorick"],
  },
  "Ancient Joker": {
    name: "Ancient Joker",
    description:
      "Each played card with [suit] gives X1.5 Mult when scored, suit changes at end of round",
    rarity: 2,
    synergies: [
      "Acrobat",
      "Blueprint",
      "Brainstorm",
      "Burnt Joker",
      "Castle",
      "Cavendish",
      "Constellation",
      "DNA",
      "Dusk",
      "Even Steven",
      "Gluttonous Joker",
      "Greedy Joker",
      "Hack",
      "Hologram",
      "Lusty Joker",
      "Photograph",
      "Scholar",
      "Seltzer",
      "Smeared Joker",
      "Sock and Buskin",
      "Space Joker",
      "The Tribe",
      "Walkie Talkie",
      "Wee Joker",
    ],
  },
  Burglar: {
    name: "Burglar",
    description: "When Blind is selected, gain +3 Hands and lose all discards",
    rarity: 1,
    synergies: [
      "Blueprint",
      "Brainstorm",
      "Card Sharp",
      "Cartomancer",
      "Castle",
      "Green Joker",
      "Jolly Joker",
      "Loyalty Card",
      "Marble Joker",
      "Matador",
      "Mystic Summit",
      "Ramen",
      "Ride the Bus",
      "Space Joker",
      "Spare Trousers",
      "Splash",
      "Square Joker",
      "Supernova",
      "Vagabond",
    ],
  },
  "Zany Joker": {
    name: "Zany Joker",
    description: "+12 Mult if played hand contains a Three of a Kind",
    rarity: 0,
    synergies: [
      "Crazy Joker",
      "Droll Joker",
      "Jolly Joker",
      "Mad Joker",
      "The Trio",
      "Walkie Talkie",
    ],
  },
  Campfire: {
    name: "Campfire",
    description:
      "This Joker gains X0.25 Mult for each card sold, resets when Boss Blind is defeated",
    rarity: 2,
    synergies: [
      "Astronomer",
      "Cartomancer",
      "Chaos the Clown",
      "Flash Card",
      "Luchador",
      "Perkeo",
      "Red Card",
    ],
  },
  Scholar: {
    name: "Scholar",
    description: "Played Aces give +20 Chips and +4 Mult when scored",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Certificate",
      "DNA",
      "Fibonacci",
      "Hanging Chad",
      "Odd Todd",
      "Photograph",
      "Ramen",
      "Seance",
      "Splash",
      "Steel Joker",
      "Superposition",
      "Walkie Talkie",
    ],
  },
  Castle: {
    name: "Castle",
    description:
      "This Joker gains +3 Chips per discarded [suit] card, suit changes every round",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Banner",
      "Burglar",
      "Burnt Joker",
      "Delayed Gratification",
      "Drunkard",
      "Gluttonous Joker",
      "Greedy Joker",
      "Merry Andy",
      "Ramen",
      "Smeared Joker",
      "Trading Card",
      "Yorick",
    ],
  },
  "Wily Joker": {
    name: "Wily Joker",
    description: "+100 Chips if played hand contains a Three of a Kind",
    rarity: 0,
    synergies: ["Half Joker", "The Trio", "Walkie Talkie", "Zany Joker"],
  },
  "Even Steven": {
    name: "Even Steven",
    description:
      "Played cards with even rank give +4 Mult when scored (10, 8, 6, 4, 2)",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Odd Todd",
      "Ride the Bus",
      "Steel Joker",
      "Walkie Talkie",
      "Wee Joker",
    ],
  },
  "Gift Card": {
    name: "Gift Card",
    description:
      "Add $1 of sell value to every Joker and Consumable card at end of round",
    rarity: 0,
    synergies: [
      "Cartomancer",
      "Ceremonial Dagger",
      "Luchador",
      "Perkeo",
      "Showman",
      "Swashbuckler",
    ],
  },
  "Ice Cream": {
    name: "Ice Cream",
    description: "+100 Chips -5 Chips for every hand played",
    rarity: 0,
    synergies: ["Popcorn", "Throwback", "Turtle Bean", "Wee Joker"],
  },
  Drunkard: {
    name: "Drunkard",
    description: "+1 discard each round",
    rarity: 0,
    synergies: [
      "Banner",
      "Burnt Joker",
      "Card Sharp",
      "Castle",
      "Delayed Gratification",
      "Faceless Joker",
      "Hit the Road",
      "Mail-In Rebate",
      "Seance",
      "Superposition",
      "Trading Card",
      "Wee Joker",
      "Yorick",
    ],
  },
  "Joker Stencil": {
    name: "Joker Stencil",
    description: "X1 Mult for each empty Joker slot. Joker Stencil included",
    rarity: 1,
    synergies: ["Certificate", "Seance"],
  },
  "Scary Face": {
    name: "Scary Face",
    description: "Played face cards give +30 Chips when scored",
    rarity: 0,
    synergies: [
      "Business Card",
      "Hanging Chad",
      "Midas Mask",
      "Pareidolia",
      "Smiley Face",
      "Sock and Buskin",
      "Splash",
    ],
  },
  "Shoot the Moon": {
    name: "Shoot the Moon",
    description: "Each Queen held in hand gives +13 Mult",
    rarity: 0,
    synergies: [
      "Baron",
      "Certificate",
      "DNA",
      "Half Joker",
      "Juggler",
      "Midas Mask",
      "Mime",
      "Reserved Parking",
      "Ride the Bus",
      "Smiley Face",
    ],
  },
  "Baseball Card": {
    name: "Baseball Card",
    description: "Uncommon Jokers each give X1.5 Mult",
    rarity: 2,
    synergies: [
      "Blackboard",
      "Bloodstone",
      "Blueprint",
      "Brainstorm",
      "Cloud 9",
      "Glass Joker",
      "Hologram",
      "Luchador",
      "Lucky Cat",
      "Oops! All 6s",
      "Rocket",
      "Shortcut",
      "Sixth Sense",
      "To the Moon",
    ],
  },
  "Square Joker": {
    name: "Square Joker",
    description: "This Joker gains +4 Chips if played hand has exactly 4 cards",
    rarity: 0,
    synergies: [
      "Burglar",
      "Cartomancer",
      "Four Fingers",
      "Green Joker",
      "Half Joker",
      "Jolly Joker",
      "Mad Joker",
      "Photograph",
      "Spare Trousers",
      "Splash",
      "Wee Joker",
    ],
  },
  Yorick: {
    name: "Yorick",
    description: "This Joker gains X1 Mult every 23 [23] cards discarded",
    rarity: 3,
    synergies: [
      "Burnt Joker",
      "Canio",
      "Castle",
      "Drunkard",
      "Faceless Joker",
      "Hit the Road",
      "Juggler",
      "Mail-In Rebate",
      "Merry Andy",
      "Mystic Summit",
      "Perkeo",
      "Triboulet",
    ],
  },
  Perkeo: {
    name: "Perkeo",
    description:
      "Creates a Negative copy of 1 random consumable card in your possession at the end of the shop",
    rarity: 3,
    synergies: [
      "8 Ball",
      "Blueprint",
      "Brainstorm",
      "Campfire",
      "Canio",
      "Cartomancer",
      "Chicot",
      "Cloud 9",
      "Constellation",
      "Fortune Teller",
      "Gift Card",
      "Hallucination",
      "Seance",
      "Sixth Sense",
      "Superposition",
      "Triboulet",
      "Vagabond",
      "Yorick",
    ],
  },
  "Abstract Joker": {
    name: "Abstract Joker",
    description: "+3 Mult for each Joker card",
    rarity: 0,
    synergies: ["Ceremonial Dagger", "Madness", "Ramen", "Riff-Raff"],
  },
  "The Trio": {
    name: "The Trio",
    description: "X3 Mult if played hand contains a Three of a Kind",
    rarity: 2,
    synergies: [
      "Cloud 9",
      "Half Joker",
      "The Duo",
      "The Family",
      "The Order",
      "The Tribe",
      "Walkie Talkie",
      "Zany Joker",
    ],
  },
  Bootstraps: {
    name: "Bootstraps",
    description: "+2 Mult for every $5 you have",
    rarity: 1,
    synergies: [
      "Bull",
      "Cloud 9",
      "Marble Joker",
      "Matador",
      "Rocket",
      "To the Moon",
    ],
  },
  "Wrathful Joker": {
    name: "Wrathful Joker",
    description:
      "Played cards with Spade suit icon Spade suit give +3 Mult when scored",
    rarity: 0,
    synergies: [
      "Droll Joker",
      "Gluttonous Joker",
      "Greedy Joker",
      "Lusty Joker",
      "Smeared Joker",
      "Steel Joker",
    ],
  },
  Hologram: {
    name: "Hologram",
    description:
      "This Joker gains X0.25 Mult every time a playing card is added to your deck",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Baseball Card",
      "Canio",
      "Certificate",
      "Cloud 9",
      "DNA",
      "Green Joker",
      "Marble Joker",
      "Red Card",
      "Seance",
      "Wee Joker",
    ],
  },
  Arrowhead: {
    name: "Arrowhead",
    description:
      "Played cards with Spade suit icon Spade suit give +50 Chips when scored",
    rarity: 1,
    synergies: [
      "Bloodstone",
      "Certificate",
      "Droll Joker",
      "Onyx Agate",
      "Rough Gem",
      "Seance",
      "Smeared Joker",
    ],
  },
  Juggler: {
    name: "Juggler",
    description: "+1 hand size",
    rarity: 0,
    synergies: [
      "Baron",
      "Card Sharp",
      "Half Joker",
      "Merry Andy",
      "Mime",
      "Seance",
      "Shoot the Moon",
      "Stuntman",
      "Troubadour",
      "Turtle Bean",
      "Yorick",
    ],
  },
  "Driver's License": {
    name: "Driver's License",
    description:
      "X3 Mult if you have at least 16 Enhanced cards in your full deck",
    rarity: 2,
    synergies: [],
  },
  "Glass Joker": {
    name: "Glass Joker",
    description:
      "This Joker gains X0.75 Mult for every Glass Card that is destroyed",
    rarity: 1,
    synergies: [
      "Baseball Card",
      "Canio",
      "Cartomancer",
      "Certificate",
      "DNA",
      "Erosion",
      "Hack",
      "Lucky Cat",
      "Onyx Agate",
      "Oops! All 6s",
      "Pareidolia",
      "Splash",
      "Steel Joker",
      "Stone Joker",
      "Trading Card",
      "Wee Joker",
    ],
  },
  "Ride the Bus": {
    name: "Ride the Bus",
    description:
      "This Joker gains +1 Mult per consecutive hand played without a scoring face card",
    rarity: 0,
    synergies: [
      "Burglar",
      "Business Card",
      "Cartomancer",
      "Even Steven",
      "Hack",
      "Marble Joker",
      "Midas Mask",
      "Odd Todd",
      "Pareidolia",
      "Reserved Parking",
      "Shoot the Moon",
      "Smiley Face",
      "Splash",
      "Trading Card",
    ],
  },
  Luchador: {
    name: "Luchador",
    description: "Sell this card to disable the current Boss Blind",
    rarity: 0,
    synergies: [
      "Baseball Card",
      "Blueprint",
      "Brainstorm",
      "Campfire",
      "Cartomancer",
      "Chicot",
      "Diet Cola",
      "Gift Card",
      "Invisible Joker",
      "Pareidolia",
    ],
  },
  "Raised Fist": {
    name: "Raised Fist",
    description:
      "Adds double the rank of lowest ranked card held in hand to Mult",
    rarity: 0,
    synergies: ["Baron", "Certificate", "Half Joker", "Mime", "Stuntman"],
  },
  "Walkie Talkie": {
    name: "Walkie Talkie",
    description: "Each played 10 or 4 gives +10 Chips and +4 Mult when scored",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Dusk",
      "Even Steven",
      "Flower Pot",
      "Hack",
      "Hanging Chad",
      "Jolly Joker",
      "Mad Joker",
      "Ramen",
      "Scholar",
      "Seeing Double",
      "Seltzer",
      "Shortcut",
      "Smeared Joker",
      "Sock and Buskin",
      "Spare Trousers",
      "Steel Joker",
      "Superposition",
      "The Duo",
      "The Family",
      "The Order",
      "The Trio",
      "Zany Joker",
    ],
  },
  Misprint: {
    name: "Misprint",
    description: "+? Mult",
    rarity: 0,
    synergies: [],
  },
  Banner: {
    name: "Banner",
    description: "+30 Chips for each remaining discard",
    rarity: 0,
    synergies: [
      "Castle",
      "Delayed Gratification",
      "Drunkard",
      "Green Joker",
      "Jolly Joker",
      "Merry Andy",
      "Ramen",
    ],
  },
  Hallucination: {
    name: "Hallucination",
    description:
      "1 in 2 chance to create a Tarot card when any Booster Pack is opened",
    rarity: 0,
    synergies: [
      "Bloodstone",
      "Fortune Teller",
      "Oops! All 6s",
      "Perkeo",
      "Red Card",
    ],
  },
  "Turtle Bean": {
    name: "Turtle Bean",
    description: "+5 hand size, reduces by 1 each round",
    rarity: 1,
    synergies: [
      "Half Joker",
      "Ice Cream",
      "Juggler",
      "Popcorn",
      "Ramen",
      "Seltzer",
      "Stuntman",
      "Throwback",
      "Troubadour",
    ],
  },
  Erosion: {
    name: "Erosion",
    description:
      "+4 Mult for each card below [the deck's starting size] in your full deck",
    rarity: 1,
    synergies: ["Canio", "Glass Joker", "Seance", "Trading Card"],
  },
  Seltzer: {
    name: "Seltzer",
    description: "Retrigger all cards played for the next 10 hands",
    rarity: 1,
    synergies: [
      "Ancient Joker",
      "Business Card",
      "Hack",
      "Photograph",
      "Turtle Bean",
      "Walkie Talkie",
    ],
  },
  Superposition: {
    name: "Superposition",
    description:
      "Create a Tarot card if poker hand contains an Ace and a Straight (Must have room)",
    rarity: 0,
    synergies: [
      "Crazy Joker",
      "Drunkard",
      "Fortune Teller",
      "Four Fingers",
      "Greedy Joker",
      "Perkeo",
      "Scholar",
      "Shortcut",
      "Walkie Talkie",
    ],
  },
  "Half Joker": {
    name: "Half Joker",
    description: "+20 Mult if played hand contains 3 or fewer cards.",
    rarity: 0,
    synergies: [
      "Baron",
      "Blue Joker",
      "Burnt Joker",
      "Card Sharp",
      "Certificate",
      "Green Joker",
      "Jolly Joker",
      "Juggler",
      "Marble Joker",
      "Mime",
      "Raised Fist",
      "Ramen",
      "Reserved Parking",
      "Shoot the Moon",
      "Space Joker",
      "Splash",
      "Square Joker",
      "Steel Joker",
      "Stone Joker",
      "Stuntman",
      "Supernova",
      "The Duo",
      "The Trio",
      "Troubadour",
      "Turtle Bean",
      "Wee Joker",
    ],
  },
  "Lusty Joker": {
    name: "Lusty Joker",
    description:
      "Played cards with Heart suit icon Heart suit give +3 Mult when scored",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Bloodstone",
      "Droll Joker",
      "Gluttonous Joker",
      "Greedy Joker",
      "Oops! All 6s",
      "Smeared Joker",
      "Steel Joker",
      "The Idol",
      "Wrathful Joker",
    ],
  },
  Splash: {
    name: "Splash",
    description: "Every played card counts in scoring",
    rarity: 0,
    synergies: [
      "Burglar",
      "Business Card",
      "Flower Pot",
      "Glass Joker",
      "Greedy Joker",
      "Green Joker",
      "Half Joker",
      "Hiker",
      "Jolly Joker",
      "Pareidolia",
      "Ride the Bus",
      "Scary Face",
      "Scholar",
      "Seeing Double",
      "Smiley Face",
      "Square Joker",
      "The Idol",
    ],
  },
  "Mail-In Rebate": {
    name: "Mail-In Rebate",
    description: "Earn $5 for each discarded [rank], rank changes every round",
    rarity: 0,
    synergies: ["Drunkard", "Yorick"],
  },
  Photograph: {
    name: "Photograph",
    description: "First played face card gives X2 Mult when scored",
    rarity: 0,
    synergies: [
      "Ancient Joker",
      "Certificate",
      "Dusk",
      "Hanging Chad",
      "Onyx Agate",
      "Pareidolia",
      "Scholar",
      "Seltzer",
      "Sock and Buskin",
      "Square Joker",
      "The Idol",
      "Triboulet",
      "Wee Joker",
    ],
  },
  Supernova: {
    name: "Supernova",
    description:
      "Adds the number of times poker hand has been played this run to Mult",
    rarity: 0,
    synergies: [
      "Burglar",
      "Burnt Joker",
      "Card Sharp",
      "Cartomancer",
      "Crazy Joker",
      "Green Joker",
      "Half Joker",
      "Marble Joker",
      "Space Joker",
      "Spare Trousers",
    ],
  },
  "The Duo": {
    name: "The Duo",
    description: "X2 Mult if played hand contains a Pair",
    rarity: 2,
    synergies: [
      "Half Joker",
      "Jolly Joker",
      "The Family",
      "The Order",
      "The Tribe",
      "The Trio",
      "Walkie Talkie",
    ],
  },
  "Droll Joker": {
    name: "Droll Joker",
    description: "+10 Mult if played hand contains a Flush",
    rarity: 0,
    synergies: [
      "Arrowhead",
      "Bloodstone",
      "Crazy Joker",
      "Four Fingers",
      "Gluttonous Joker",
      "Greedy Joker",
      "Jolly Joker",
      "Lusty Joker",
      "Mad Joker",
      "Onyx Agate",
      "Rough Gem",
      "Smeared Joker",
      "The Tribe",
      "Wrathful Joker",
      "Zany Joker",
    ],
  },
  Certificate: {
    name: "Certificate",
    description:
      "When round begins, add a random playing card with a random seal to your hand",
    rarity: 1,
    synergies: [
      "Arrowhead",
      "Baron",
      "Blueprint",
      "Brainstorm",
      "Bull",
      "Burnt Joker",
      "Constellation",
      "DNA",
      "Fibonacci",
      "Flash Card",
      "Fortune Teller",
      "Glass Joker",
      "Hack",
      "Half Joker",
      "Hit the Road",
      "Hologram",
      "Joker Stencil",
      "Lucky Cat",
      "Mime",
      "Onyx Agate",
      "Photograph",
      "Raised Fist",
      "Scholar",
      "Shoot the Moon",
      "Space Joker",
      "Vampire",
      "Wee Joker",
    ],
  },
  "Faceless Joker": {
    name: "Faceless Joker",
    description:
      "Earn $5 if 3 or more face cards are discarded at the same time",
    rarity: 0,
    synergies: [
      "Blueprint",
      "Brainstorm",
      "Drunkard",
      "Joker",
      "Merry Andy",
      "Pareidolia",
      "Yorick",
    ],
  },
  Obelisk: {
    name: "Obelisk",
    description:
      "This Joker gains X0.2 Mult per consecutive hand played without playing your most played poker hand",
    rarity: 2,
    synergies: ["Cartomancer", "Constellation", "Madness", "Spare Trousers"],
  },
  "Rough Gem": {
    name: "Rough Gem",
    description:
      "Played cards with Diamond suit icon Diamond suit earn $1 when scored",
    rarity: 1,
    synergies: [
      "Arrowhead",
      "Bloodstone",
      "Droll Joker",
      "Greedy Joker",
      "Onyx Agate",
      "Pareidolia",
      "Smeared Joker",
    ],
  },
  Hiker: {
    name: "Hiker",
    description: "Every played card permanently gains +5 Chips when scored",
    rarity: 1,
    synergies: ["Hack", "Splash"],
  },
};

export default jokerdata;
